name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: npm run zip
      - name: Set package version
        id: get-version
        run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT
      - name: Upload Release Asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.event.release.tag_name }}" "./dynamic-dates-${{ steps.get-version.outputs.version }}.zip"
